### ISSUE TITLE
Version control when editing a page

### ISSUE THREAD

**Issue by KeldNielsen86** [Laravel-Backpack/PageManager#128]
It would be a very nice feature if the pagemanger support version control, so the pages updated using pagemanager is saved to a new row and a version tag is added. in order for admins to know on which time a certain version is added

**Comment by tabacitu** [comment]
Thanks for the suggestion @KeldNielsen86 . We'll keep it in mind when we create a _better_ PageManager. The current one won't receive many extra features... it's more of an example on how to create one... a boilerplate... rather than a complete solution.

Sorry to close 2 of your issues in a row 😅 feels odd, but as I said, we really don't plan on adding many features to the current PageManager.
