### ISSUE TITLE
can i use image type field with pagemanager module?

### ISSUE THREAD

**Issue by c1t1zen** [Laravel-Backpack/PageManager#19]
Hey
i tried to use page manager and it works when i add new text type field but when i change the type to image it does not work
and i get error page:

QueryException in Connection.php line 770: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'extras' at row 1 (SQL: update `pages` set `extras` = {"meta_title":"dfdsfdsf","meta_description":"fffff","meta_keywords":null,"slide1":"data:image\/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPkAAAD5CAYAAADlT5OQAAAgAElEQVR4nLy955Mj15mv2d92I3bj3pFET8pLM5JGmju62pi5s7FzTYzR1

is there a solution to do that?

**Comment by OwenMelbz** [comment]
If you read the error, it tells you why its breaking. 

If you still don't understand the error, despite it saying "data too long for column extras" best to google it.

https://www.google.co.uk/search?q=mysql+Data+too+long+for+column&oq=mysql+Data+too+long+for+column&aqs=chrome..69i57.8299j0j4&sourceid=chrome&ie=UTF-8

Its best to learn how to debug code, and search google/stack overflow etc rather than just asking as this is a generic php/mysql error and not backpack specific, although even better is to read the error messages :D

I'll close this issue to keep the area tidy as its not actually backpack specific

**Comment by tabacitu** [comment]
@c1t1zen , changing your MySQL column type to BLOB or LONGBLOB should fix it for you. Cheers!

**Comment by c1t1zen** [comment]
Thank you @tabacitu 
i think extra field only for text or textarea 
if i need to add more attribute i should create new column as image and define it in model for page manager module
