### ISSUE TITLE
Class Backpack\PageManager\App\Http\Controllers\Admin\PageCrudController does not exist

### ISSUE THREAD

**Issue by carlosrgzm** [Laravel-Backpack/PageManager#28]
I'm trying to use this package but after following installation spteps I've this error 
"Class Backpack\PageManager\App\Http\Controllers\Admin\PageCrudController does not exist"
when I go to /admin/page

Has anyone have this problem too?

**Comment by tabacitu** [comment]
Boy, this must have been frustrating, to find out there's a typo... Sorry for that and thanks for submitting the PR.

Cheers!

**Comment by reeslo** [comment]
I have the issue :'(

**Comment by carlosrgzm** [comment]
It's already fixed, it was a typo. 

https://github.com/carlosrgzm/PageManager/commit/39df42d7fecedbba9b702d0acf9dc0e5ab6d2789

Cheers!

**Comment by tabacitu** [comment]
Yes, thank you @carlosrgzm . If anybody else has this issue past this point, a ```composer update``` and republishing the config file should fix it for you.

Cheers!

**Comment by andersonmadeira** [comment]
Copying these two changed files to the server will fix this issue: https://github.com/Laravel-Backpack/PageManager/commit/1954a08da0943cfd9e9b4617880be402852bb829

**Comment by alexkb** [comment]
@tabacitu if you do try `composer update` currently you still get the broken version. I think this might be because you created the wrong tag a couple of releases ago (1.1.17) which is greater than the new tag 1.1.9. To get the update currently users should instead type `composer require backpack/pagemanager:1.1.9`.

**Comment by andersonmadeira** [comment]
@alexkb Exactly. Confirmed.

**Comment by alexkb** [comment]
Thanks @andersonmadeira.

Another issue I found was that after applying this fix, my custom Page Model stopped being detected by Backpack (basically my Model's mutators weren't being fired on creates/edits).

I tried a dozen things (including updating Laravel and Backpack/Crud which I gave up on), but eventually the only thing that worked was creating a PageCrudController and setting my Page Model namespace in the constructor. 

I believe the reason why the Model worked fine previously was because my Model's were stored in the `App\Models` namespace (which pagemanager was incorrectly looking for).

The reason why I came across this thread was originally because I had OP's error when I deployed to a Linux server (never came across it on Mac for some reason, even though they're both case sensitive filesystems).
