### ISSUE TITLE
[Proposal] Sidebars?

### ISSUE THREAD

**Issue by AbbyJanke** [Laravel-Backpack/PageManager#33]
I was curious if there was some interest/want on the option of a "Sidebar" for pages, I was thinking similar to how "Page Templates" are used but instead of a whole new "SidebarTemplates" file, just add a new folder `pages\sidebars` and scan the directory. Because there generally shouldn't be much content dynamically being made in those (from what i can think of) save a step of editing that file and more bloat.

Thoughts/feedback?

Note: I have a sorta working prototype of doing it simply by working with the PageTempaltes files but think it might be something a lot of people are interested in.

**Comment by AbbyJanke** [comment]
I also think we should add a filter to the `getSidebars()` function where it grabs `getMethods()`  I think we should change it to only list public. Currently with my version I am building the sidebar through the templates file, but the `getTemplates` lists all methods so it includes even my private methods of `getSidebars` and `getSidebarArray`.

**Comment by AbbyJanke** [comment]
Did some more work on implementing this because as I was using functions to load the views I switched to just scanning the directory and adding a `select` field to the page template. One thing I do want to possibly look into is still having sidebars built in with editable options similar to how pages is. So maybe a `page type` kind of like how on the MenuCrud has `link type` only this would be option of `page` or `sidebar` and it auto populate from sidebars within the DB?

**Comment by tabacitu** [comment]
Hi @AbbyJanke ,

I myself never felt the need for a SidebarsManager, for my projects, but I'll let others pitch in with their opinion. Let's leave the issue open until then. It could easily be a separate package, a tutorial or a snippet in the upcoming "snippets" section on [BackpackForLaravel.com](http://backpackforlaravel.com)

The way I usually use sidebars, I almost always need create a [View Composer](https://laravel.com/docs/5.4/views#view-composers), because they use some content that's not available in the main view. This might be something to consider.

Cheers!

**Comment by Justproof** [comment]
Was getTemplates() implemented?

I want to index all the pages into a "recent articles" sidebar, but would like to know if such a call exists.

**Comment by lloy0076** [comment]
@tabacitu @AbbyJanke - is this still alive?

**Comment by lloy0076** [comment]
I pronounce this ... not currently active. Feel free to re-open if needed.
