### ISSUE TITLE
PHP Fatal error:  Trait 'App\PageTemplates' not found in

### ISSUE THREAD

**Issue by andreasnrb** [Laravel-Backpack/PageManager#96]
# Bug report
PHP Fatal error:  Trait 'App\PageTemplates' not found in /.../vendor/backpack/pagemanager/src/app/Http/Controllers/Admin/PageCrudController.php on line 17
### What I did:
Required package
### What I expected to happen:
Autoload files to generate
### What happened:
PHP Fatal Error
### Backpack, Laravel, PHP, DB version:
4.0.0, 6.0.3, 7.2.1

### Fix
Change PageTemplate namespace to the correct one in PageTemplate from "App" to "Backpack\PageManager". Update PageCrudController accordingly.

**Comment by tabacitu** [comment]
Hi @andreasnrb ,

Actually, the ```PageTemplates.php``` file is better placed in your ```App``` folder, since it's something you'd be heavily modifying - to create your own page templates. In the current version we've changed the order of the installation steps. You'll notice creating this ```App\PageTemplates.php``` file is the very first step of the installation - https://github.com/Laravel-Backpack/PageManager#install

That [first step of the installation process](https://github.com/Laravel-Backpack/PageManager#install) should fix it for you.

Cheers!
